[package]
name = "custom_enum_traits"
version = "0.2.0"
edition = "2018"
license = "MIT"
description = "A set of traits for dealing with enums."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
